enableTelemetry: false

logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard

nodeLinker: node-modules

packageExtensions:
  "@opentelemetry/node@*":
    dependencies:
      "@opentelemetry/plugin-http": "*"
      "@opentelemetry/plugin-https": "*"
      "@opentelemetry/plugin-pg-pool": "*"
      "@opentelemetry/plugin-pg": "*"
      "@opentelemetry/plugin-ioredis": "*"
      "@opentelemetry/plugin-mongodb": "*"
  "@opentelemetry/plugin-ioredis@*":
    dependencies:
      "@opentelemetry/semantic-conventions": "*"
  "@opentelemetry/plugin-mongodb@*":
    dependencies:
      "@opentelemetry/semantic-conventions": "*"
  "@bufbuild/protoc-gen-es@*":
    dependencies:
      "@bufbuild/protobuf": "*"
  "@eslint/eslintrc@*":
    dependencies:
      js-yaml: "*"
  "@brillout/import@*":
    dependencies:
      "react-dom": "*"
  "react-dom@*":
    dependencies:
      "react": "*"
  "@joshwooding/vite-plugin-react-docgen-typescript@*":
    dependencies:
      vite: "*"
  "@storybook/builder-vite@*":
    dependencies:
      "@storybook/preview-web": "*"
      "@storybook/react-vite": "*"
      vite: "*"
  "@storybook/core-common@*":
    dependencies:
      "@storybook/react-vite": "*"
  "@storybook/react-dom-shim@*":
    dependencies:
      react-dom: "*"
  babel-plugin-relay@*:
    dependencies:
      "@babel/runtime": "*"
  baseui@*:
    dependencies:
      styletron-standard: "*"
  jest-config@*:
    dependencies:
      ts-node: "*"
  ts-node@*:
    dependencies:
      typescript: "*"
  vite-plugin-monaco-editor@*:
    dependencies:
      esbuild: "*"
  graphql-yoga@*:
    dependencies:
      graphql: "*"
  "@pothos/core@*":
    peerDependencies:
      graphql: "*"
  "@envelop/opentelemetry@*":
    dependencies:
      "@envelop/core": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.5.1.cjs
