version: v0.11.0

dsn: memory

# Settings for both anti-CSRF and session cookies
cookies:
  domain: ".anthaathi.localhost"
  path: /
  same_site: Lax

session:
  cookie:
    name: anthaathi_session

serve:
  public:
    base_url: http://accounts.anthaathi.localhost:4443/
    cors:
      enabled: true
      allowed_origins:
        - http://*.anthaathi.localhost:4443
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
      exposed_headers:
        - Content-Type
  admin:
    base_url: http://kratos:4434/

selfservice:
  default_browser_return_url: http://accounts.anthaathi.localhost:4443/
  allowed_return_urls:
    - http://accounts.anthaathi.localhost:4443/
    - http://tenant.anthaathi.localhost:4443/
    - http://esg.anthaathi.localhost:4443/
    - http://task.anthaathi.localhost:4443/

  methods:
    oidc:
      enabled: true
      config:
        base_redirect_uri: https://tolocalhost.com
        providers:
          - id: google
            provider: google
            label: Google
            client_id: "CLIENT_ID"
            client_secret: "CLIENT_SECRET"
            mapper_url: "file:///etc/config/kratos/mappers/google.jsonnet"
            scope:
              - email
              - profile
            requested_claims:
              id_token:
                email:
                  essential: true
                email_verified:
                  essential: true
                given_name:
                  essential: true
                family_name: null
    password:
      enabled: true
    totp:
      config:
        issuer: Kratos
      enabled: true
    lookup_secret:
      enabled: true
    link:
      enabled: true
    code:
      enabled: true

  flows:
    error:
      ui_url: http://accounts.anthaathi.localhost:4443/v1/error

    settings:
      ui_url: http://accounts.anthaathi.localhost:4443/
      privileged_session_max_age: 30m
      required_aal: highest_available

    recovery:
      enabled: true
      ui_url: http://accounts.anthaathi.localhost:4443/v1/recovery
      use: link
      lifespan: 8h
      after:
        default_browser_return_url: http://accounts.anthaathi.localhost:4443/security/change-password

    verification:
      enabled: true
      ui_url: http://accounts.anthaathi.localhost:4443/v1/verification
      use: link
      after:
        default_browser_return_url: http://crm.anthaathi.localhost:4443/

    logout:
      after:
        default_browser_return_url: http://accounts.anthaathi.localhost:4443/v1/sign-in

    login:
      ui_url: http://accounts.anthaathi.localhost:4443/v1/sign-in
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: http://accounts.anthaathi.localhost:4443/v1/sign-up
      after:
        password:
          hooks:
            - hook: session

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE_REALLY
  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: smtp://mailslurper:25/?disable_starttls=true
    from_address: hello@example.org
    from_name: My Company
